# Generated by Django 3.2 on 2021-11-01 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211101_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-date_published',)},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='modified_date',
            new_name='date_modified',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='published_date',
            new_name='date_published',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='modified_date',
            new_name='date_modified',
        ),
    ]
